### PR TITLE
[MISC][NT] Aligned icons and copy for alert component with icon variant

### PR DESCRIPTION
**Pull request by nobeltws**
**Changes**
Fixed alignment of alert component to center contents when icon is rendered

- [delete] branch

**Changelog entry**

- [WARNING] Center contents when icon is rendered in `Alert`

- You may refer to this [BOOKINGSG-6398](https://jira.ship.gov.sg/browse/BOOKINGSG-6398)

### CODE REVIEW

**Comment by nobeltws** [comment]
oops, my bad. i removed the `align-items: center` css.
for single line it is now like this:
image

With max collapse height:
image

**Comment by qroll** [comment]
annoyingly, now the small variant becomes misaligned, probably due to the different text height on the font

Screenshot 2024-10-29 at 12 27 09 PM

what if we remove the custom height `height: 1.625rem;`, and apply `height: 1lh` and `align-items: center` on AlertIconWrapper? this forces it to match the height of the first line

**Comment by nobeltws** [comment]
Updated with your suggestions. i checked in storybook, looks good~

**Review by qroll — APPROVED** [review]
thanks for the fix!

**Pull request merged**
